steps:
- name: "gcr.io/cloud-builders/npm"
  args: ["ci"]
  dir: "server"

- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$SHORT_SHA", "."]
  dir: "server"

- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$SHORT_SHA"]

- name: "gcr.io/cloud-builders/gcloud"
  args: [
    "run",
    "deploy",
    "${_SERVICE_NAME}",
    "--image",
    "gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$SHORT_SHA",
    "--region",
    "${_REGION}",
    "--platform",
    "managed",
    "--allow-unauthenticated"
  ]
  dir: "server"

images:
- "gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$SHORT_SHA"

substitutions:
  _IMAGE_NAME: "ai-sihat-server"
  _SERVICE_NAME: "ai-sihat"
  _REGION: "us-central1"

timeout: "1200s"
